### ISSUE TITLE
Thank you very much for your code, which has helped me a lot! But I have a question for you. Thank you

### ISSUE THREAD

**Issue by liubaoning111** [sotiraslab/AgileFormer#5]
/home/liubn/anaconda3/envs/swin_umamba/lib/python3.10/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/home/liubn/anaconda3/envs/swin_umamba/lib/python3.10/site-packages/torchvision/image.so: undefined symbol: _ZN3c1017RegisterOperatorsD1Ev'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
tvdcn is installed, using it for deformable convolution
Traceback (most recent call last):
  File "/home/liubn/anaconda3/envs/swin_umamba/lib/python3.10/site-packages/natten/functional.py", line 32, in <module>
    from natten import libnatten  # type: ignore
ImportError: /home/liubn/anaconda3/envs/swin_umamba/lib/python3.10/site-packages/natten/libnatten.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN2at4cuda19getDevicePropertiesEl

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/liubn/0-149liubaoning/43-AgileFormer-main/train.py", line 12, in <module>
    from networks.agileFormer_2d import AgileFormer2D as ViT_seg
  File "/home/liubn/0-149liubaoning/43-AgileFormer-main/networks/agileFormer_2d.py", line 3, in <module>
    from .agileFormer_sys_2d import AgileFormerSys2D
  File "/home/liubn/0-149liubaoning/43-AgileFormer-main/networks/agileFormer_sys_2d.py", line 9, in <module>
    from .nat_2d import NeighborhoodAttention2D
  File "/home/liubn/0-149liubaoning/43-AgileFormer-main/networks/nat_2d.py", line 30, in <module>
    from natten.functional import na2d_av, na2d_qk_with_bias
  File "/home/liubn/anaconda3/envs/swin_umamba/lib/python3.10/site-packages/natten/__init__.py", line 24, in <module>
    from .functional import (
  File "/home/liubn/anaconda3/envs/swin_umamba/lib/python3.10/site-packages/natten/functional.py", line 34, in <module>
    raise ImportError(
ImportError: Failed to import NATTEN's CPP backend. This could be due to an invalid/incomplete install. Please uninstall NATTEN (pip uninstall natten) and re-install with the correct torch build: shi-labs.com/natten .

**Comment by peijieq** [comment]
@liubaoning111 Could you try uninstalling the natten and reinstalling it ? This could resolve this problem most time. The issue may be caused if you installed the natten incorrectly, or the natten is incompatible with some of your packages you installed afterwards. In particular, installing the tvdcn after installing natten may update your torch and cuda version. So I recommend to install tvdcn before installing natten (check the torch and cuda version after installing tvdcn).
